name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web-app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install pipenv
      - run: pipenv install --dev

      - name: Run Tests with Coverage
        run: pipenv run pytest --cov=. --cov-report=term-missing

      - name: Enforce 80% test coverage
        run: |
          COVERAGE=$(pipenv run coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80%" >&2
            exit 1
          fi

  deploy:
    name: Deploy to Droplet
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "."
          target: "/opt/blackjack-web-app"
          strip_components: 0

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /opt/blackjack-web-app
            docker ps -q --filter "name=blackjack-web-app_mongodb_1" | grep -q . && docker stop blackjack-web-app_mongodb_1 && docker rm blackjack-web-app_mongodb_1 || echo "No mongodb container to remove"
            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d
